version: '2'

services:
  tarantool:
    container_name: mytarantool
    image: tarantool/tarantool:1.7
    command: tarantool /usr/local/share/tarantool/app.init.lua
    ports:
      - 3301:3301
    volumes:
      - /home/baski/Projects/tarantool/app:/usr/local/share/tarantool
      - /home/baski/tarantool/data:/var/lib/tarantool
